---
blocks:
- minecraft:allow
- minecraft:azalea
- minecraft:bamboo_fence
- minecraft:bamboo_mosaic
- minecraft:bamboo_planks
- minecraft:budding_amethyst
- minecraft:camera
- minecraft:cherry_fence
- minecraft:cherry_planks
- minecraft:conduit
- minecraft:crimson_fungus
- minecraft:crimson_nylium
- minecraft:crimson_roots
- minecraft:deny
- minecraft:dripstone_block
- minecraft:end_gateway
- minecraft:end_portal
- minecraft:flowering_azalea
- minecraft:frog_spawn
- minecraft:honey_block
- minecraft:lodestone
- minecraft:moss_block
- minecraft:moss_carpet
- minecraft:nether_sprouts
- minecraft:powder_snow
- minecraft:target
- minecraft:torchflower
- minecraft:unknown
- minecraft:warped_fungus
- minecraft:warped_nylium
- minecraft:warped_roots
items:
- minecraft:agent_spawn_egg
- minecraft:allay_spawn_egg
- minecraft:archer_pottery_shard
- minecraft:armor_stand
- minecraft:arms_up_pottery_shard
- minecraft:axolotl_bucket
- minecraft:axolotl_spawn_egg
- minecraft:balloon
- minecraft:bamboo_chest_raft
- minecraft:bamboo_raft
- minecraft:bamboo_sign
- minecraft:banner_pattern
- minecraft:bat_spawn_egg
- minecraft:bee_spawn_egg
- minecraft:birch_chest_boat
- minecraft:blaze_spawn_egg
- minecraft:bordure_indented_banner_pattern
- minecraft:brush
- minecraft:camel_spawn_egg
- minecraft:camera
- minecraft:campfire
- minecraft:carrot_on_a_stick
- minecraft:cat_spawn_egg
- minecraft:cave_spider_spawn_egg
- minecraft:chest_boat
- minecraft:chest_minecart
- minecraft:chicken_spawn_egg
- minecraft:cod_bucket
- minecraft:cod_spawn_egg
- minecraft:command_block_minecart
- minecraft:cow_spawn_egg
- minecraft:creeper_banner_pattern
- minecraft:creeper_spawn_egg
- minecraft:crossbow
- minecraft:dark_oak_chest_boat
- minecraft:diamond_horse_armor
- minecraft:dolphin_spawn_egg
- minecraft:donkey_spawn_egg
- minecraft:drowned_spawn_egg
- minecraft:elder_guardian_spawn_egg
- minecraft:elytra
- minecraft:empty_map
- minecraft:enchanted_book
- minecraft:end_crystal
- minecraft:ender_dragon_spawn_egg
- minecraft:ender_eye
- minecraft:enderman_spawn_egg
- minecraft:endermite_spawn_egg
- minecraft:evoker_spawn_egg
- minecraft:field_masoned_banner_pattern
- minecraft:filled_map
- minecraft:firework_rocket
- minecraft:firework_star
- minecraft:flower_banner_pattern
- minecraft:fox_spawn_egg
- minecraft:frog_spawn_egg
- minecraft:ghast_spawn_egg
- minecraft:globe_banner_pattern
- minecraft:glow_squid_spawn_egg
- minecraft:glow_stick
- minecraft:goat_horn
- minecraft:goat_spawn_egg
- minecraft:golden_horse_armor
- minecraft:guardian_spawn_egg
- minecraft:hoglin_spawn_egg
- minecraft:hopper_minecart
- minecraft:horse_spawn_egg
- minecraft:husk_spawn_egg
- minecraft:ice_bomb
- minecraft:iron_golem_spawn_egg
- minecraft:iron_horse_armor
- minecraft:jungle_chest_boat
- minecraft:kelp
- minecraft:lead
- minecraft:leather_horse_armor
- minecraft:lingering_potion
- minecraft:llama_spawn_egg
- minecraft:lodestone_compass
- minecraft:magma_cube_spawn_egg
- minecraft:mangrove_chest_boat
- minecraft:mojang_banner_pattern
- minecraft:mooshroom_spawn_egg
- minecraft:mule_spawn_egg
- minecraft:name_tag
- minecraft:nether_sprouts
- minecraft:npc_spawn_egg
- minecraft:oak_chest_boat
- minecraft:ocelot_spawn_egg
- minecraft:panda_spawn_egg
- minecraft:parrot_spawn_egg
- minecraft:phantom_spawn_egg
- minecraft:pig_spawn_egg
- minecraft:piglin_banner_pattern
- minecraft:piglin_brute_spawn_egg
- minecraft:piglin_spawn_egg
- minecraft:pillager_spawn_egg
- minecraft:polar_bear_spawn_egg
- minecraft:powder_snow_bucket
- minecraft:prize_pottery_shard
- minecraft:pufferfish_bucket
- minecraft:pufferfish_spawn_egg
- minecraft:rabbit_spawn_egg
- minecraft:rapid_fertilizer
- minecraft:ravager_spawn_egg
- minecraft:recovery_compass
- minecraft:saddle
- minecraft:salmon_bucket
- minecraft:salmon_spawn_egg
- minecraft:sheep_spawn_egg
- minecraft:shield
- minecraft:shulker_spawn_egg
- minecraft:silverfish_spawn_egg
- minecraft:skeleton_horse_spawn_egg
- minecraft:skeleton_spawn_egg
- minecraft:skull_banner_pattern
- minecraft:skull_pottery_shard
- minecraft:slime_spawn_egg
- minecraft:sniffer_spawn_egg
- minecraft:snow_golem_spawn_egg
- minecraft:soul_campfire
- minecraft:sparkler
- minecraft:spawn_egg
- minecraft:spider_spawn_egg
- minecraft:spruce_chest_boat
- minecraft:stray_spawn_egg
- minecraft:strider_spawn_egg
- minecraft:tadpole_bucket
- minecraft:tadpole_spawn_egg
- minecraft:tnt_minecart
- minecraft:torchflower_seeds
- minecraft:trader_llama_spawn_egg
- minecraft:trident
- minecraft:tropical_fish_bucket
- minecraft:tropical_fish_spawn_egg
- minecraft:turtle_spawn_egg
- minecraft:vex_spawn_egg
- minecraft:vindicator_spawn_egg
- minecraft:wandering_trader_spawn_egg
- minecraft:warden_spawn_egg
- minecraft:warped_fungus_on_a_stick
- minecraft:witch_spawn_egg
- minecraft:wither_skeleton_spawn_egg
- minecraft:wither_spawn_egg
- minecraft:wolf_spawn_egg
- minecraft:zoglin_spawn_egg
- minecraft:zombie_horse_spawn_egg
- minecraft:zombie_pigman_spawn_egg
- minecraft:zombie_villager_spawn_egg
...
